#!/usr/bin/env python3
"""'Fixes' the FITS image generated by Difmap when using the stokes 'PI' (polarization intensity).
In converts it to Stokes 'I' so the image can be used by any other software without problems.
"""
import argparse
from astropy.io import fits

__version__ = '1.0'

def main():
    usage = "%(prog)s [-h] [-v]  <fits image>"
    description="""'Fixes' the FITS image generated by Difmap when using the stokes 'PI' (polarization intensity).
    In converts it to Stokes 'I' so the image can be used by any other software without problems.
    """
    parser = argparse.ArgumentParser(description=description, prog='fix_difmap_image.py', usage=usage)
    parser.add_argument('fitsimage', type=str, help='Path to the FITS image.')
    parser.add_argument('-v', '--version', action='version', version='%(prog)s {}'.format(__version__))
    args = parser.parse_args()

    try:
        with fits.open(args.fitsimage, mode='update') as ffile:
            if 'CRVAL4' in ffile[0].header:
                if -9.0001 < ffile[0].header['CRVAL4'] < -8.999:
                    ffile[0].header['CRVAL4'] = 1.0
                    ffile.flush(output_verify='ignore')
    except fits.VerifyError as e:
        print(f"WARNING: VerifyWarning: {e}")
        print("Continuing from here...")


if __name__ == '__main__':
    main()
